### ISSUE TITLE
StringLike assumes toString is a noop

### ISSUE THREAD

**Issue by mkeskells** [rorygraves/scalac_perf#29]

**Comment by mkeskells** [comment]
should be just snapping toString to a val 

Need to see if this has an effect though - just from code inspection so far

**Comment by RobinStephenson** [comment]
Please assign me

**Comment by RobinStephenson** [comment]
Strawman improvements made this reduntant, but created a PR with the benchmarks here https://github.com/scala/scala/pull/6666
