### ISSUE TITLE
scala.reflect.internal.Symbols.Symbol#ownerChain is called too many times when compile aka-actor

### ISSUE THREAD

**Issue by cryptom-dev** [rorygraves/scalac_perf#37]
we probably can make it a var and only update it when onwer changes, so that it won’t get re-computed every time.

In terms of performance test, I think this cannot be easily microbenchmarked but perf_tester (macro benchmark) would be a good choice.

**Comment by mkeskells** [comment]
duplicate of https://github.com/rorygraves/scalac_perf/issues/3

**Comment by rorygraves** [comment]
Closed as duplicate
