### ISSUE TITLE
List filter/filterNot needs to be reapplied

### ISSUE THREAD

**Issue by rorygraves** [rorygraves/scalac_perf#58]
the List filter/filterNot changes got backed out here:

https://github.com/scala/scala/commit/76babbb6728e5daf4fb95444273f6f8e0a4098d7
because of an issue with Mima - they and their associated tests should be reapplied -
I think these will end up in strawman rather than base of 2.13

**Comment by cryptom-dev** [comment]
https://github.com/scala/scala/pull/6386 merged
